### ISSUE TITLE
rxMode version string replaced where it shouldn't

### ISSUE THREAD

**Issue by Mrrraou** [roxas75/rxTools#400]
Sometime, the "Ver." string is replaced by "RX-E" or "RX-S" where it shouldn't, like some games (Badge Arcade, for example), or some apps (devMenu for example).
This is a minor issue.

**Comment by piratesephiroth** [comment]
yeah this happens since the old rxTools

**Comment by mariogamer2** [comment]
Already fixed in commit 58d8c985b8c1cd5115ecb0aa65e9f5fdb5c4e025 .

**Comment by Mrrraou** [comment]
Totally unrelated.

**Comment by mariogamer2** [comment]
?

**Comment by urherenow** [comment]
Ha! Yes, this still happens on the latest build. Just boot rxmode emunand and open Badge Arcade to duplicate.
